apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:<YOUR_USERNAME>/argocd-test.git
    targetRevision: HEAD
    path: infra
  destination: 
    server: https://kubernetes.default.svc
    namespace: documentation
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true