apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.3
        name: guestbook-ui
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      # activeService specifies the service to update with the new template hash at time of promotion.
      # This field is mandatory for the blueGreen update strategy.
      activeService: rollout-bluegreen-guestbook-ui-active
      # previewService specifies the service to update with the new template hash before promotion.
      # This allows the preview stack to be reachable without serving production traffic.
      # This field is optional.
      previewService: rollout-bluegreen-guestbook-ui-preview

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-guestbook-ui-active
spec:
  selector:
    app: guestbook-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-guestbook-ui-preview
spec:
  selector:
    app: guestbook-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080